### ISSUE TITLE
ERROR: Could not build wheels for seislib, cartopy, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by sapphire0103** [fmagrini/seislib#11]
I am trying to install seislib on a Ubuntu system. All of the dependencies seem to download fine and I downloaded the dependencies for cartopy as well after getting this error at first.  

here is the error after pip install seislib:

gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
      compilation terminated.
      error: command '/home/ubuntu/anaconda3/envs/seislib/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cartopy
Failed to build seislib cartopy
ERROR: Could not build wheels for seislib, cartopy, which is required to install pyproject.toml-based projects

I have gcc installed:

$ gcc --version
gcc (conda-forge gcc 12.2.0-19) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I've already done sudo apt-get install libgeos-dev and sudo apt-get install libproj-dev. and pip3 install --upgrade pip setuptools wheel
how do I fix this issue?

note: the full results after running pip install seislib is very long which is why i didn't copy and paste it but if it will help I can.

**Comment by fmagrini** [comment]
Did you install all needed dependencies following the SeisLib [documentation](https://seislib.readthedocs.io/en/latest/installation.html)?

If so, your problem is probably related to [this](https://askubuntu.com/questions/637014/gcc-error-trying-to-exec-cc1plus-execvp-no-such-file-or-directory). Please try
  sudo apt-get install g++

Then reinstall all dependencies and finally ``seislib``

**Comment by sapphire0103** [comment]
Thank you!
I used anaconda version of g++ and it worked:

conda install -c conda-forge gxx
