### ISSUE TITLE
Lat Lon Datum

### ISSUE THREAD

**Issue by eikmeier-cn** [fmagrini/seislib#13]
Dear Dr.Magrini

Thanks for sharing the package.

I have a doubt about the lat lon format to be used. It seems to me that we should use degrees, correct? With which Datum (SRIGAS2000, SAD69...)?

**Comment by fmagrini** [comment]
Latitude and longitude are usually in degrees and span the ranges -90/90 and -180/180. Please make sure this is the case for the particular function you intend to use by visiting the online [documentation](https://seislib.readthedocs.io/en/latest/) or typing, in you Python GUI, "help(function_name)".

**Comment by eikmeier-cn** [comment]
Thanks for the answer, Dr. Magrini. And about the Datum?

**Comment by fmagrini** [comment]
I am not sure what Datum you are talking about. If you are referring to the SeismicTomography class, velocity should be in m/s, analogous to ref_vel (see the documentation of SeismicTomography.add_data).

Please ensure to only write on this page when you encounter an actual issue. I am closing this thread.
