### ISSUE TITLE
Getting requirements to build wheel ... error

### ISSUE THREAD

**Issue by rabuwest** [fmagrini/seislib#14]
Hi Magrini, I have followed the installation process from the documentation and downloaded all necessary dependencies. But I am having trouble installing seislib, encountering the above error. The error seems to originate from the setup_cython_extension and the specific output from the error is:

UnboundLocalError: local variable 'extra_link_args' referenced before assignment.

I am using a MacOS Monterey enviroment with a clang version 14.0.0

**Comment by fmagrini** [comment]
OpenMP, which is used in the Cython codes for multiprocessing computation, is not supported by Clang. To fix this issue, please install gcc through Homebrew by running the command `brew install gcc` in your terminal. After installing gcc, please reinstall seislib.

Let me know if this resolves the issue, or if you encounter any further problems.

**Comment by rabuwest** [comment]
That solved the issue. 
Thanks!
