### ISSUE TITLE
Clarification on Issues with NumPy 1.22

### ISSUE THREAD

**Issue by amole-arup** [fmagrini/seislib#15]
Thank you for all your work on this package. Please could you update your documentation to explain why there are problems with NumPy 1.22 and whether you are planning to make SeisLib compatible with newer versions of NumPy at some point.

**Comment by fmagrini** [comment]
Thanks for your comment. I have just tried to run seislib in a Python 3.9 + NumPy 1.26 environment and could not reproduce my old issues. I have removed that comment from the documentation.

**Comment by amole-arup** [comment]
Thank you so much for your swift response!
