### ISSUE TITLE
Add basic usage notebooks

### ISSUE THREAD

**Issue by juvenalandres** [fmagrini/seislib#16]
Hello,

I've been using your software for a little while now and it's been very useful. However, I feel the documentation is not very intuitive as of now. Have you considered adding a few notebooks with basic examples of usage? 

Thank you

**Comment by fmagrini** [comment]
Thank you for your feedback. I plan to add notebooks in the future as time allows. If you haven't already, please note that each class in SeisLib includes a usage example. These should help you leverage all its main functionalities.
