### ISSUE TITLE
Is there any demo data for learn usage?

### ISSUE THREAD

**Issue by xichaoqiang** [fmagrini/seislib#3]
Dear Dr.Magrini

Thanks for sharing this great package.

Is there any demo earthquake and ambient noise data for this package?

So we can learn how to use this package properly.

And I can try  add some jupyter notebooks for other people for tutorial purposes.

Thank you very much for your work.

Best regards,
Xi

**Comment by fmagrini** [comment]
Dear Xi,

I am working on the online documentation. I should be able to complete it in a couple of weeks. Note that the codes are extensively documented, and you can simply access them by typing help(class) or help(class.method) in your favorite GUI.

In few words, you can use the following classes:
- seislib.an.AmbientNoiseVelocity (automated calculation of ambient-noise dispersion curves)
- seislib.an.AmbientNoiseAttenuation (automated calculation of ambient-noise attenuation)
- seislib.an.ANDownloader (automated download of continuous seismograms in the right format)
- seislib.eq.EQVelocity (automated calculation of earthquake-based dispersion curves)
- seislib.eq.TwoStationMethod (called under the hood by seislib.eq.EQVelocity)
- seislib.an.EQDownloader (automated download of teleseismic earthquakes in the right format)
- seislib.tomography.EqualAreaGrid (allowing you to parameterize the Earth using an equal-area grid)
- seislib.tomography.SeismicTomography (least-squares imaging of surface-wave velocities)

and the functions from the modules:
- seislib.plotting (utility functions for plotting your results)
- seislib.colomaps (that allow you to use the Fabio Crameri colormaps https://www.fabiocrameri.ch/colourmaps/)
- seislib.an (several utility functions called by the AmbientNoise classes)

As for the example data, I will probably add some on GitHub in the next few weeks. You can easily download them with the above downloader classes for now.

Best,
Fabrizio

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
