### ISSUE TITLE
please help me to know why dispersion curve retrieved  is 0(zero)

### ISSUE THREAD

**Issue by Hmishra1** [fmagrini/seislib#9]
''

from seislib.eq import EQVelocity
src='/home/parallels/data/data'
eq = EQVelocity(src, component='Z')

eq.prepare_data(azimuth_tolerance=7, 
                    distmin=None, 
                    distmax=2500, 
                    min_no_events=8)

print(eq)

''
After running this code I got

EVENTS PROCESSED: 4/49
EVENTS PROCESSED: 8/49
EVENTS PROCESSED: 12/49
EVENTS PROCESSED: 16/49
EVENTS PROCESSED: 20/49
EVENTS PROCESSED: 24/49
EVENTS PROCESSED: 28/49
EVENTS PROCESSED: 32/49
EVENTS PROCESSED: 36/49
EVENTS PROCESSED: 40/49
EVENTS PROCESSED: 44/49
EVENTS PROCESSED: 48/49

RAYLEIGH-WAVE VELOCITY FROM TELESEISMIC EARTHQUAKES (TWO-STATION METHOD)
=========================================================================
EVENTS: 49
RECEIVERS: 70
TRIPLETS (EPICENTER-RECEIVERS) AVAILABLE: 101
DISPERSION CURVES RETRIEVED: 0
=========================================================================
SOURCE DIR: /home/parallels/data/data
SAVE DIR: /home/parallels/data/eq_velocity/Z

**Comment by Hmishra1** [comment]
from seislib.eq import EQVelocity
eq = EQVelocity(src, component='Z')
eq.prepare_data(azimuth_tolerance=7, 
                    distmin=None, 
                    distmax=2500, 
                    min_no_events=8)

print(eq)


RAYLEIGH-WAVE VELOCITY FROM TELESEISMIC EARTHQUAKES (TWO-STATION METHOD)
=========================================================================
EVENTS: 50
RECEIVERS: 70
TRIPLETS (EPICENTER-RECEIVERS) AVAILABLE: 101
DISPERSION CURVES RETRIEVED: 0
=========================================================================
SOURCE DIR: /home/parallels/data/data
SAVE DIR: /home/parallels/data/eq_velocity/Z

**Comment by fmagrini** [comment]
Hello,

You did not get any curve simply because you haven't started the calculations yet. Please make sure that you finish reading the EQVelocity example in the SeisLib documentation. (The example continues after eq.prepare_data()).

As this is the third issue you raise in three days, and none of them could really be considered "issues", I must ask you to think twice before doing so.

Regards
